socketio/socket.io-redis-adapter

- index.js
- package.json
- test/index.js
Previously socket.io-redis was listening for the whole pattern socket.io#* and the messages were sent to socket.io#id. This means that all the socket.io servers will receive all messages, even if the server does not use that namespace, even if there are no client listening to any of those rooms on them. If there are some nodes which send a lot of message, all the socket.io servers will have 100% cpu really quickly.
I changed it to use socket.io#namespace#room in order to be able to filter the messages on the redis server already, so the socket.io servers will receive only the messages they need to receive.
> Make use of redis pub-sub for improved performance

- README.md
Remove broken build status caused by the name change of the github organization.
> Working travis build status

- README.md
Use of undefined 'adapter' presumably supposed to be the redis module export in this example?
> Fix undefined 'adapter' variable in example

- README.md
- index.js
- package.json
- test/index.js
You should use `return_buffers` instead of `detect_buffers` as `detect_buffers` is no longer work with pub/sub (since 2.0.0). Also `return_buffers` is not working in version 2.2.0-2.2.5 due to bug NodeRedis/node_redis#911, but it works in 2.3.0.
> Replace detect_buffers with return_buffers

- package.json
This updates node-redis to the latest version
> Updated node-redis dependency to 2.4.2, which matches socket.io-emitter

- .gitignore
- README.md
- index.js
Hi,
I added an option named subEvent, so we could supply an ioredis client by providing the proper event as discussed here https://github.com/socketio/socket.io-redis/issues/60.
With this option we could use ioredis directly which would be great as it's a well deserved redis client.
> Add support to ioredis

- index.js
Hopefully, the title says all.
Well, we're using a lot of namespaces. and there is performance problem.
> Return early when channels mismatch to skip expensive msgpack decoding

- index.js
My initial approach was to use `url.parse()` from the Node.js URL module to get the hostname and port. This did work, but I noticed that redis also lets you specify the database index and other options via the URL, so it seemed better to pass it wholesale to the `createClient` call if specified.
> Fixes #93 by passing full URI to redis.createClient when specified

- index.js
- test/index.js
It seems `Adapter.prototype.broadcast.call(this, packet, opts);` actually modifies the `packet` object, by removing any binary data attached.
Reference: https://github.com/socketio/socket.io-parser/blob/master/index.js#L196
Fix #112, close #113
> Fix an issue when broadcasting binary data between nodes.

- README.md
- index.js
- test/index.js
This pull request adds the ability to get all clients IDs connected to a room or rooms. It's up to date with `Adapter` so a call to [Namespace#clients(fn:Function)](https://github.com/socketio/socket.io#namespaceclientsfnfunction) will return the same result as `RedisAdapter.clients(rooms:Array, fn:Function)`
> Get all clients in a room across all nodes

- index.js
Closes https://github.com/socketio/socket.io-redis/pull/77
> [refactor] Use this.channel to construct the name of a channel

- README.md
- index.js
- test/index.js
- test/ioredis.js
This PR refactors the way requests are sent between nodes. The `subJson`
client has been removed, the subClient now listens to three channels by
default:
- the usual channel, where the message are broadcast
- the request channel, where any node can request information (for now,
the clients in a given rooms or the rooms for a given client)
- the response channel, where a node will receive answer to its requests
Fixes https://github.com/socketio/socket.io-redis/issues/138 (no more `subJson`)
Closes https://github.com/socketio/socket.io-redis/issues/143 (add `clientRooms()` method)
@artofspeed would that suit your needs?
> Refactor requests between nodes and add `clientRooms` method

- index.js
This was causing a timeout error on `.clients` and `.clientRooms` because of this check https://github.com/socketio/socket.io-redis/blob/f2dd9fea22963a697666f135247d6f0de1ee7f29/index.js#L252-Lundefined
`request.msgCount` was an int and `request.numsub` was a string.
> numsub and msgCount are different type

- README.md
- index.js
- test/index.js
With that subscription event the `return_buffers` flag is not needed anymore.
Closes https://github.com/socketio/socket.io-redis/issues/91
Also closes https://github.com/socketio/socket.io-redis/pull/116
> subEvent now defaults to `messageBuffer`

- .travis.yml
- index.js
- package.json
Fixes #40. Alternative to #105.
My benchmarks showed `msgpack-lite` being a little bit faster encoding and a little bit slower decoding than `msgpack`. `msgpack5` on the other hand was 5x slower doing both.
> Replace msgpack with msgpack-lite

- README.md
- index.js
- test/index.js
This PR add some useful (well, I guess) methods:
- `allRooms`: Returns the list of all rooms.
- `remoteJoin`: Makes the socket with the given id join the room.
- `remoteLeave`: Makes the socket with the given id leave the room.
- `customRequest`: Sends a request to every nodes, that will respond through the `customHook` method.
Closes https://github.com/socketio/socket.io-redis/pull/154, closes https://github.com/socketio/socket.io-redis/issues/125
Also closes https://github.com/socketio/socket.io-redis/issues/68
cc @connected-yzhang @infnada @jreeter @mp3il
> Add some useful methods

- index.js
- test/index.js
Please, check carefully before merging, because I'm not sure if I did it right. Thanks!
> remoteDisconnect feature.

- History.md
Closes https://github.com/socketio/socket.io-redis/issues/185.
> Update History.md regarding the `return_buffers` option

- index.js
The callback was triggered before the socket has actually joined/left the room.
Fix https://github.com/socketio/socket.io-redis/issues/198
> Fix remoteJoin/remoteLeave methods

- index.js
- package.json
Starting from version 3.0 (2.0.1 works fine) on some systems socket.io-redis package fatals with error **SyntaxError: Identifier 'sendAck' has already been declared**, this pull request solves this problem, sendAck methods changed with anonymous versions.
> https://github.com/socketio/socket.io-redis/issues/211

- .travis.yml
- README.md
- index.js
- package.json
- test/index.js
This follows #46. Each node will now listen to only three channels:
- `socket.io#<namespace>#*`: used when broadcasting
- `socket.io-request#<namespace>#`: used for requesting information (ex: get every room in the cluster)
- `socket.io-response#<namespace>#`: used for responding to requests
We keep the benefits of #46 since:
- messages from other namespaces are ignored
- when emitting to a single room, the message is sent to
`socket.io#<namespace>#<my-room>`, so listeners can check whether they
have the room before unpacking the message (which is CPU consuming).
But there is no need to subscribe / unsubscribe every time a socket
joins or leaves a room (which is also CPU consuming when there are
thousands of subscriptions).
> Use pattern matching at the namespace level

- index.js
The message is now published to `socket.io#<namespace>#<my-room>#`, instead of `socket.io#<namespace>#<my-room>` (introduced by https://github.com/socketio/socket.io-redis/pull/217, breaking the [protocol](https://github.com/socketio/socket.io-redis#protocol))
Fixes https://github.com/socketio/socket.io-redis/issues/220
> Fix broken protocol in 5.0.0

- index.js
- test/index.js
Request object does not have a `.requestid` property so requests were not being cleaned up and `.requests` was leaking memory in every `Redis` instance.
Fixes #224
> Uses the requestid from response when deleting requests

- History.md
Add note about compatibility, as described in https://github.com/socketio/socket.io-redis/releases/tag/5.0.0
> Add note about compatibility

- index.js
In order to solve the issues #267 and #210 I added a function in charge of the calculation of the numsub.
The function will:
- Check the configuration of redis (standalone, sentinel or cluster).
- If the configuration is cluster, send "pubsub numsub channel" to all the nodes of the cluster.
- Make the sum of all the responses.
- Return the value of numsub.
I tried it on the diferent configurations and it seems to work.
I couldn't run the test on my local for the master so I didn't do it for my changes.
It is my first contribution so if you have any advice you're welcome !
> [fix] Update the way to calculate numsub (#267, #210)

- lib/index.ts
- test/index.js
This line in the README suggests that you should be able to use the server to send messages to all clients in a room. When I do that I end up with the stacktrace below error.
`io.to('room42').emit('hello', "to all clients in 'room42' room");`
Not sure if I have understood how to use the server/namespace correctly, but I found this bug in my app when I wanted to update to socketio v3. In my app I want the server to broadcast a message to a specific room and that triggers the following stacktrace. 
```
TypeError: opts.except is not iterable
at RedisAdapter.broadcast (/usr/src/node_modules/socket.io-redis/dist/index.js:255:34)
at Namespace.emit (/usr/src/node_modules/socket.io/dist/namespace.js:175:22)
at Server.<computed> [as emit] (/usr/src/node_modules/socket.io/dist/index.js:442:33)
at …
```
> Use server/namespace to broadcast

- README.md
`allSockets` was missing the await keyword. See: https://socket.io/docs/v3/server-api/#namespace-allSockets
> docs: fix allSockets example

- README.md
Should be `createAdapter` for the ES6 and TS examples.
> Doc update to fix incorrect use of import

- package-lock.json
- package.json
This updates the [`uid2`](https://www.npmjs.com/package/uid2) dependency from 0.0.3 to 1.0.0 (its latest release) which has the following changes (see its [HISTORY.md](https://github.com/coreh/uid2/blob/master/HISTORY.md) for full details):
* Uses `crypto.randomBytes` instead of `crypto.pseudoRandomBytes` https://github.com/coreh/uid2/commit/e492a9db2a9892dc13a5f55e4ae28ff9af2add64
* Adds `-_` to generated unique IDs https://github.com/coreh/uid2/commit/a3b8def77e211a7fd8f244666a0e1d3edacf0d16
* Improves generation time of an ID by 15% https://github.com/coreh/uid2/commit/3cfd2cc9555b772f3e361ca60a98c0931d504b41
The first change would only matter to clients that are using a version of node < 4.0.0, but this repo only supports >= 10 so that's not really a problem. This does also …
> Update uid2 dependency from 0.0.3 to 1.0.0

- package-lock.json
- package.json
This is a follow-up to https://github.com/socketio/socket.io-redis-emitter/pull/113
I found out that the way `Date` instances are serialized changes from notepack.io 2 to 3, so after upgrading `socket.io-redis-emitter`, Dates get decoded as eg. `[ -1, <Buffer 90 b8 57 00 63 37 5d 19> ]`. Seems like the library version needs to be kept in sync.
CC @darrachequesne 🤗
> Update notepack.io to ~3.0.1

- lib/index.ts
- test/index.ts
- When the close function is called it will (p)unsubscribe from the channels it (p)subscribed to in the constructor.
- Added a test to verify that channels are being unsubscribed from when close is called.
This is implemented in conjunction with https://github.com/socketio/socket.io/pull/4602 to fix https://github.com/socketio/socket.io-redis-adapter/issues/480.
> Implement adapter.close function

- lib/index.ts
- package-lock.json
`registerFriendlyErrorHandler` method adds a listener on pub and sub client. Let's remove it in `close()`
> Add friendlyErrorHadler cleanup to prevent memory leak

- lib/index.ts
https://github.com/socketio/socket.io-redis-adapter/issues/494
> Detect node-redis RedisCluster client and use corresponding sendCommand()

- lib/cluster-adapter.ts
- lib/index.ts
- lib/sharded-adapter.ts
- [fix: serverCount method should return result](https://github.com/socketio/socket.io-redis-adapter/pull/497/commits/1781819e142b95edf3f80709c381eb45b2f154a4)
- [perf: no need call Date.now() in loops](https://github.com/socketio/socket.io-redis-adapter/pull/497/commits/7882a58d91b5ba277fae495f7f4da840f6e3d3a3)
- [feat: use forEach instead map if no value return](https://github.com/socketio/socket.io-redis-adapter/pull/497/commits/f09bfc3958f3c15071bd5e68b7a2a6a9a1455520)
> serverCount should have `return` in map function

- lib/cluster-adapter.ts
If `fetchSockets()` is called shortly after the adapter was initialized, the server count may still return `0`, causing this to fail with `timeout reached: only 0 responses received out of -1`.
The problem is [handled correctly](https://github.com/socketio/socket.io-redis-adapter/blob/4c372a8f73b32ae19dea69b938e441d3dac97e52/lib/index.ts#L739) in the regular adapter, so using the same approach here.
> fix(sharded): expectedResponseCount in fetchSockets()

- lib/util.ts
This is a proposed fix for #528.
This pull request introduces a change to the sharded adapter's `SSUBSCRIBE` logic: Previously, for each dynamic channel/room, a unique listener was added to the client's `smessageBuffer`. This approach led to a large number of listeners (resulting in `MaxListenersExceededWarning`), especially in scenarios with many dynamic channels. Further, listeners were not being removed when unsubscribing, leading to a memory leak.
The new implementation replaces the multiple listeners with a single `smessageBuffer` listener. This listener is registered once and handles all dynamic channels by maintaining specific channel handlers in a `Map`. Listeners are added to this `Map` in `SSUBSCRIBE` and removed from the `Map` in `SUNSUBSCRIBE`.
Thanks for your review! 🙏
> fix(sharded): SSUBSCRIBE smessageBuffer memory leak (#528)

- lib/sharded-adapter.ts
- test/index.ts
- test/specifics.ts
Fixes #524 by adding a check for `expectSingleResponse` flag, which is added for `RemoteSocket` instances [here](https://github.com/socketio/socket.io/blob/54dabe5bffeb705fd006729725dd2fa194f70ecf/lib/broadcast-operator.ts#L491). I couldn't find any documentation about that flag, but it seems to be the only way of identifying this case and it does fix the problem.
> fix(sharded): private room broadcast in dynamic mode

- lib/sharded-adapter.ts
- test/test-runner.ts
As an alternative solution for #524, this:
- adds a new option `dynamicPrivateChannels`, which allows creating separate channels even for private rooms; defaults to `false` so there's no change in default behavior,
- includes the fix from #525 which is needed when the option is set to `false`
> feat(sharded): add an option for dynamic private channels
